### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'templates'. Did you mean: 'set_templates'?

### ISSUE THREAD

**Issue by VahedCivil** [kerrickstaley/genanki#131]
**Description**
While creating the package, I encounter the following message:

**_Traceback (most recent call last):
  File "g:\Training\Abaqus\Python Scripting for Abaqus -  By Vahed Mamqaderi\Test python codes\Test 44 - Anki in Python\main.py", line 36, in <module>
    anki.SavePackage('my_package_test.apkg')
  File "g:\Training\Abaqus\Python Scripting for Abaqus -  By Vahed Mamqaderi\Test python codes\Test 44 - Anki in Python\anki_generate\genanki_en_to_fa_vocabs.py", line 119, in SavePackage
    self.Package.write_to_file(packageFn)
  File "D:\Program Files\Python311\Lib\site-packages\genanki\package.py", line 40, in write_to_file
    self.write_to_db(cursor, timestamp, id_gen)
  File "D:\Program Files\Python311\Lib\site-packages\genanki\package.py", line 60, in write_to_db
    deck.write_to_db(cursor, timestamp, id_gen)
  File "D:\Program Files\Python311\Lib\site-packages\genanki\deck.py", line 63, in write_to_db
    {model.model_id: model.to_json(timestamp, self.deck_id) for model in self.models.values()})
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\genanki\deck.py", line 63, in <dictcomp>
    {model.model_id: model.to_json(timestamp, self.deck_id) for model in self.models.values()})
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\genanki\model.py", line 92, in to_json
    for ord_, tmpl in enumerate(self.templates):
                                ^^^^^^^^^^^^^^
AttributeError: 'Model' object has no attribute 'templates'. Did you mean: 'set_templates'?_**

**To reproduce**
I have uploaded parts of my code for easier review.
[anki_generate.zip](https://github.com/kerrickstaley/genanki/files/14925210/anki_generate.zip)

**genanki version**
**genanki-0.13.1**

**Comment by VahedCivil** [comment]
Templates has incorrect format.
